version: "3"

tasks:
  lint:
    desc: "Lint"
    cmds:
      - npm run lint

  format:
    desc: "Format"
    cmds:
      - npx prettier . --write

  check-format:
    desc: "Check format"
    cmds:
      - npx prettier . --check

  type-check:
    desc: "Type-check"
    cmds:
      - npm run type-check
  dev:
    desc: "Start the Next.js development server"
    cmds:
      - npm run dev

  build:
    desc: "Build the Next.js project"
    cmds:
      - npm run build

  start:
    desc: "Start the Next.js production server"
    cmds:
      - node .next/standalone/server.js

  build-and-start:
    desc: "Build an Start a production NextJS server"
    cmds:
      - task: build
      - task: start

  unit-test-watch:
    desc: "Run unit tests in watch mode"
    cmds:
      - npm run test:watch

  unit-test-ci:
    desc: "Run unit tests in a single run"
    cmds:
      - npm run test:ci

  unit-test-coverage:
    desc: "Run unit tests in a single run with coverage report"
    cmds:
      - npm run test:coverage

  e2e-test-ui:
    desc: "Run end-to-end tests in ui mode"
    cmds:
      - npm run e2e-test:ui

  e2e-test-ci:
    desc: "Run end-to-end tests in ci mode"
    cmds:
      - npm run e2e-test:ci
