services:
  frontend:
    container_name: brain-frontend
    build:
      context: ./frontend/
    ports:
      - "3000:3000"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      - backend

  backend:
    container_name: brain-backend
    build:
      context: ./backend/
    ports:
      - "42069:42069"
    volumes:
      - ./backend/config.json:/app/config.json
    environment:
      BRAIN_POSTGRES_HOST: "${BRAIN_POSTGRES_HOST:-database}"
      BRAIN_POSTGRES_USER: "${POSTGRES_USER:-adminson}"
      BRAIN_POSTGRES_PORT: "${BRAIN_POSTGRES_PORT:-5432}"
      BRAIN_POSTGRES_DATABASE: "${BRAIN_POSTGRES_DATABASE:-brain}"
      BRAIN_POSTGRES_PASSWORD: "${BRAIN_POSTGRES_PASSWORD:-password}"
    depends_on:
      - database

  database:
    image: postgres:16.2-alpine3.19
    container_name: brain-database
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_USER: "${POSTGRES_USER:-adminson}"
      POSTGRES_DB: "${POSTGRES_DB:-brain}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER:-adminson} -d ${POSTGRES_DB:-brain}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
