version: "3"

tasks:
  db-up:
    desc: "Up a postgres instance"
    cmds:
      - docker compose up database {{.CLI_ARGS}}

includes:
  frontend:
    taskfile: ./frontend/Taskfile.yaml
    dir: ./frontend

  backend:
    taskfile: ./backend/Taskfile.yaml
    dir: ./backend

  docs:
    taskfile: ./docs/Taskfile.yaml
    dir: ./docs
