version: "3"

tasks:
  run-web:
    desc: "Run the web handler"
    cmds:
      - go run ./cmd/web

  build-web:
    desc: "Build the web handler"
    cmds:
      - go build -o brain.test ./cmd/web

  lint:
    desc: "Lint the backend"
    cmds:
      - golangci-lint run

  format:
    desc: "Format code"
    cmds:
      - go fmt ./...

  check-format:
    desc: "Check if code is formated"
    cmds:
      - test -z "$(gofmt -l .)"

  test-light:
    desc: "Run lighter tests"
    cmds:
      - gotestsum -f pkgname -- -short ./...

  test-all:
    desc: "Run entire tests"
    cmds:
      - gotestsum -f pkgname

  watch-tests:
    desc: "Watch tests"
    cmds:
      - gotestsum --watch -f pkgname

  flag-heavy-tests:
    desc: "Flag a Heavy test with short so that we can skip if necessary"
    cmds:
      - go test -json -short ./... | gotestsum tool slowest --skip-stmt "testing.Short" --threshold 200ms

  coverage:
    desc: "Test coverage output to coverage.html"
    cmds:
      - gotestsum -f pkgname -- -coverprofile=c.out ./...
      - go tool cover -html=c.out -o coverage.html

  generate-docs:
    desc: "Generate swagger docs"
    cmds:
      - swag fmt
      - swag init -d ./cmd/web,internal/adapters/drivers/web -g main.go

  check-vuln:
    desc: "Check for code common vulnerabilities"
    cmds:
      - govulncheck ./...
