name: Golang CI

on:
  push:
    branches: [ "main" ]
    paths: ["backend/**"]
  pull_request:
    branches: ["main", "dev"]
    paths: ["backend/**"]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Format Check
        run: test -z "$(gofmt -l .)"

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          working-directory: backend

      - name: Build
        run: task build-web

      - name: Test with the Go CLI
        run: task test-light
